name: Playable Skyrim Together Build

on:
  workflow_dispatch:
  schedule:
    # Every Friday at 1:00 p.m. UTC
    - cron: "0 13 * * 5"
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [release]

    if: ${{ github.repository_owner == 'tiltedphoques' || github.event_name != 'schedule' }} # Disable cron runs in forks

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          # We need full history in order to create a build version string (BuildInfo.h)
          fetch-depth: 0

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

      - name: Checkout master on tag push
        if: github.ref_type == 'tag'
        # Checkout only if the tag was pushed to master
        run: (git rev-parse HEAD) -eq (git rev-parse origin/master) -and (git checkout master)

      - name: Full STR Build
        uses: ./.github/actions/full-build
        with:
          mode: releasedbg
          arch: ${{ matrix.mode }}
          artifact-name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
