name: Build windows

on:
  pull_request:
  push:
    branches:
      - master
      - bluedove
      - prerel

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [releasedbg]

    runs-on: ${{ matrix.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive --depth=1

      - name: Full STR Build
        uses: ./.github/actions/full-build
        with:
          mode: ${{ matrix.mode }}
          arch: ${{ matrix.arch }}
          artifact-name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
          config-options: "--vs_sdkver=10.0.19041.0"
